fix: add validation for CR number in promote to staging workflow and update approval job names

diff --git a/.github/workflows/core-promote-staging.yml b/.github/workflows/core-promote-staging.yml
--- a/.github/workflows/core-promote-staging.yml
+++ b/.github/workflows/core-promote-staging.yml
@@ -26,6 +26,14 @@ jobs:
             exit 1
           fi
         shell: bash
+      - name: Validate CR number
+        run: |
+          if [ -z "${{ inputs.cr_number }}" ]; then
+            echo "CR number is required."
+            exit 1
+          fi
+          echo "CR=${{ inputs.cr_number }}"
+        shell: bash
       - name: CR Information
         run: |
           echo "🚀 Staging Promotion Request"
@@ -40,26 +48,12 @@ jobs:
     steps:
       - run: echo "Security approval granted."
 
-  approve_release:
+  approve_po:
     runs-on: ubuntu-latest
     needs: approve_security
     environment: stg-approve-po
     steps:
-      - run: echo "Release/Change approval granted."
-
-  stg-deployment:
-    runs-on: ubuntu-latest
-    needs: approve_release
-    environment: stg
-    steps:
-      - name: Validate CR number
-        run: |
-          if [ -z "${{ inputs.cr_number }}" ]; then
-            echo "CR number is required."
-            exit 1
-          fi
-          echo "CR=${{ inputs.cr_number }}"
-
+      - run: echo "PO approval granted."
       - name: Checkout config repo
         uses: actions/checkout@master
         with:
